name: Release
on:
  push:
    branches:
      - main
      - 0.x
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release with release-please
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: simple
          target-branch: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}