name: Release
permissions:
  contents: write
  pull-requests: write
on:
  push:
    branches:
      - main
      - 0.x
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release with release-please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          release-type: node
          target-branch: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}